### ISSUE TITLE
Exporter panic due to a bad metric name

### ISSUE THREAD

**Issue by achaussier** [mtulio/rundeck-exporter#8]
Hello,

I have see this error, certainly caused by the `-`.

```
rundeck_exporter_1  | panic: "rundeck_counter_status_200_static_star-star" is not a valid metric name
```
Have a nice day

**Comment by mtulio** [comment]
Hi @achaussier ,

Thanks for your report.

What is your Rundeck version?

I just merge the fix #12 and create the release [v0.1.5-rc2](https://github.com/mtulio/rundeck-exporter/releases/tag/v0.1.5-rc2).

Could you please check if it was fixed?
